luraproject/lura

- examples/gin/main.go
- examples/mux/Makefile
- examples/mux/main.go
As requested in #18 , this PR shows how to integrate a cache lib into the `mux` router adapter available in the framework
> Add a cache wrapper to the mux example

- Makefile
- config/config.go
- config/config_test.go
- encoding/json.go
- encoding/json_test.go
- encoding/xml.go
- encoding/xml_test.go
As requested in #21 , this PR adds support for collections as backend responses
In order to consume backend exposing collections, users must add the `is_collection` param in the backend config:
```
{
"endpoint": "/combination/{id}",
"method": "GET",
"backend": [
{
"host": [
"https://jsonplaceholder.typicode.com"
],
"url_pattern": "/posts?userId={id}",
"is_collection": true,
"mapping": {
"collection": "posts"
}
},
{
"host": [
"https://jsonplaceholder.typicode.com"
],
"url_pattern": "/users/{id}",
"mapping": {
"email": "personal_email"
}
}
]
}
```
> accept collections as responses from backends

- router/gin/debug_test.go
- router/gin/endpoint_test.go
- router/gin/router_test.go
the last versions of the JSON response writers from the gin framework don't add a final new line, so tests are failing
> fix the gin integration tests

- proxy/proxy.go
Using Krakend to serve html content, my servers often send Set-Cookie headers.
I often have response headers like:
```
Set-Cookie: cookieName=; Expires=Thu, 01 Jan 1970 00:00:01 GMT
Set-Cookie: cookieName2=value; Path=/; Max-Age=3600
```
To forward those cookies, I am using the `Response.Metadata` field of `proxy/proxy.go`, joining cookie headers using:
```
var response proxy.Response
response.Metadata["Set-Cookie"] = strings.Join(resp.Headers["Set-Cookie"], ",")
```
and setting the header back to with
```
for header, value := range response.Metadata {
c.Header(header, value)
}
```
Increase the support for multiple Headers by introducing a Metadata
type.
solves #48
Signed-off-by: Thibault Jamet <thibault.jamet@schibsted.com>
> Use type for Metadata

- proxy/formatter.go
_Disclaimer_: I've read the ```CONTRIBUTING.md```file, but I just was trying to read the code, and learn from it doing some changes.
I think (not sure), that the code does exactly the same but with fewer lines. 
I do not know if affects performance, (I think it avoids to create ```tmp``` map when not needed) but I think that performance in building the white list  filter is not important (only used when reading the conf, I guess).
> reduce whitelisting filter creation function size

- Makefile
- config/parser.go
- proxy/factory.go
- router/gin/router.go
- router/mux/endpoint.go
- router/router.go
- sd/subscriber.go
so users can create the simplest implementations
> Support func versions of every interface

- config/config.go
- config/parser.go
- router/gin/router.go
- router/mux/router.go
define the `MaxIdleConnsPerHost` param for the default http transport layer.
> max idle connection per host

- config/config.go
as @tjamet pointed out in #65 , when both the default timeout and the endpoint timeout are not defined (aka, equal to 0) all the requests get 500 HTTP errors
Instead of throwing errors to the user, we can fallback to a hardcoded default value
> default timeout added

- proxy/merging.go
- proxy/merging_test.go
Fix https://github.com/devopsfaith/krakend/issues/80 
In commit https://github.com/devopsfaith/krakend/commit/cc67d65263ac836659a0ac190e85fa707de3fba1 there is the test that reproduces the issue, and the fix in https://github.com/devopsfaith/krakend/commit/3882217eb2dbe92ce27d7d227935285df0468217.
I've run the benchmarks, and there is also a minor improvement in speed / allocs:
Before:
```
goos: linux
goarch: amd64
pkg: krakend/proxy
BenchmarkNewMergeDataMiddleware/with_2_parts-8         	  300000	      4593 ns/op	    1360 B/op	      20 allocs/op
BenchmarkNewMergeDataMiddleware/with_3_parts-8         	  300000	      5384 ns/op	    1488 B/op	      22 allocs/op
BenchmarkNewMergeDataMiddleware/with_4_parts-8         	  200000	      5826 ns/op	    1584 B/op	      24 allocs/op
PASS
ok …
```
> Fix #80: Merge incomplete responses data

- proxy/formatter.go
- proxy/formatter_benchmark_test.go
- proxy/formatter_test.go
I found that current whitelist only allows two level depth, but I like to be able to select more in depth fields.
So I tried this change, that while using up to two level depth whitelist, it keeps running at similar speed / performance that was with previous code, but allows to select any deeper level fields.
(Removed implementation details comment part that no longer apply)
> Unlimit whitelist depth

- proxy/merging.go
- proxy/merging_test.go
- proxy/proxy.go
as requested in #78 , this PR adds a register for easy injection of custom combiners without changing the proxy (pipe) factory but the endpoint config
> combiner register added

- config/config.go
- config/parser.go
- plugin/plugin.go
- plugin/plugin_test.go
this PR adds an initial implementation of a simple plugin loader.
at this early stage, plugins are responsible for registering and kicking off their own components.
a very nice plugin candidate could be a set of martian modifiers, because they already register themselves into the martian register and users can include the new types in their martian DSL without recompiling the KrakenD binary
**I'd like to remark the experimental status of this language feature, so use with caution**
> Support golang plugins

- proxy/merging.go
- proxy/register_test.go
as detected in #81, the response combiner interface does not require a context
> Remove the context from the response combiner signature

- sd/loadbalancing.go
- sd/loadbalancing_benchmark_test.go
- sd/loadbalancing_test.go
Do not balance over a `sd.FixedSubscriber` with a single host.
> LoadBalancer optimizations

- router/gin/endpoint.go
- router/gin/endpoint_test.go
- router/gin/router.go
- router/gin/router_test.go
- router/gorilla/router.go
- router/gorilla/router_test.go
- router/mux/endpoint.go
- router/mux/endpoint_test.go
- router/mux/engine.go
- router/mux/router.go
- router/mux/router_test.go
- router/negroni/router.go
- router/negroni/router_test.go
- router/router.go
As requested in #119 , this PR adds the `X-KrakenD-Completed: true|false` header to every response returned by the KrakenD gateway
> Add an explicit header about response completeness

- proxy/factory.go
- proxy/stack_benchmark_test.go
- proxy/static.go
- proxy/static_test.go
This PR adds 'partial responses' to the KrakenD manipulation toolbox, by injecting the content of `data` field defined at the `extra_config` using the requested `strategy`.
Configuration example:
```
...
{
"endpoint": "/abc",
"extra_config": {
"github.com/devopsfaith/krakend/proxy": {
"static": {
"data" : {
"new_field_a": 42,
"new_field_b": ["data"],
"new_field_c": {"data": "b"}
},
"strategy": "incomplete"
}
}
}
}
...
```
Available strategies:
- `always` will add the data to every response
- `success` will add the data to every non-failed response
- `errored` will add the data to every failed response (error not nil)
- `complete` will add the data to every response marked as completed
- `incomplete` will add the data to every nil response or the ones marked as incomplete
This PR does not …
> Static partial responses

- proxy/request.go
- proxy/request_test.go
In order to avoid race-conditions on middlewares running at the 'not thread-safe' part of the proxy pipe (see #105 ), this PR introduces 3 helpers those components could use:
- `func CloneRequest(r *Request) *Request`
- `func CloneRequestHeaders(headers map[string][]string) map[string][]string`
- `func CloneRequestParams(params map[string]string) map[string]string`
Developers must select one of them depending on what they want to change in their middleware
> request deep copy helpers added

- proxy/http_executor.go
The HTTP backend factory should use its own HTTP client in order to isolate the pipes from other parts of the system (metric reporters, etc)
> Private http client

- router/gin/router.go
- router/gin/router_test.go
- router/gorilla/router.go
- router/mux/router.go
- router/mux/router_test.go
- router/router.go
As requested in #143 this PR adds a `RunServer` function to the `Router` `Config` struct of each router so anyone can inject it's own http server.
It also moves the old implementation to a `RunServer` function in the `router` package to be used as default.
> Decoupled http server

- .gitignore
- Makefile
- config/config.go
- config/parser.go
- router/http/router.go
- router/http/router_test.go
- router/router.go
this PR adds:
+ the required config settings for enabling the TLS layer at the router.
+ the automatic selection of the server function to call (plain or TLS)
It also moves the http related functions, vars and constants into a dedicated package. In future releases, the interface of the `router` package could deprecate the original ones.
> https enabled

- router/gin/endpoint.go
- router/gin/endpoint_test.go
- router/mux/endpoint.go
- router/mux/endpoint_test.go
endpoint timeouts should be durations, so no op is required
> Fix: endpoint timeouts

- config/config.go
- config/config_test.go
...so a fingerprint of the config can be used in other parts of the framework without passing the config itself
> Add a Hash to the service configuration

- proxy/http.go
- proxy/http_test.go
- router/router.go
- transport/http/client/executor.go
- transport/http/client/status.go
- transport/http/server/server.go
- transport/http/server/server_test.go
This PR introduces a new package `transport` so the related stuff won't pollute the `proxy` and the `router` packages.
> http transport package added

- proxy/merging.go
- proxy/merging_benchmark_test.go
- proxy/merging_test.go
As requested at #155 , this PR adds the sequential proxy merger, so backends can be called sequentially using parts of the already received responses to compose the next request.
> sequential proxy merger

- config/config.go
- config/config_test.go
- proxy/http.go
- router/gin/router.go
- router/gin/router_test.go
- router/mux/endpoint.go
- router/mux/router.go
- router/mux/router_test.go
so the gRPC methods can be defined using the same property
> delay endpoint method sanitization until required

- router/gin/endpoint.go
This is a pull request based on this issue: https://github.com/devopsfaith/krakend/issues/176
The idea is to solve the problem of having headers that are written in non camel case typing not being captured by the proxy and, therefore, not being sent along with the request.
> gin request header retrieval by canonical MIME

- router/gorilla/router.go
- router/mux/engine.go
- router/mux/router.go
- router/mux/router_test.go
- router/negroni/router.go
func Handle(pattern string, handler http.Handler)
not support method
& in my realisation of router i can not using two endpoint with different access methods
> support HTTP methods in gorilla, mux & negroni

- router/gin/endpoint.go
- router/mux/endpoint.go
#174
This commit changes behavior on 2 config fields:
"querystring_params": ["*"],
"headers_to_pass": ["*"],
Asterisk makes sending all params (headers or query string)
gin router modification
> Endpoint option: forward all query string params and headers, if needed

- proxy/shadow.go
- proxy/shadow_test.go
Adds a shadow proxy to be able to call shadow requests as requested in #130 
It looks in the `config.Backend` extra config for the "shadow" key to process the backend as shadow.
> Shadow backends

- router/mux/endpoint.go
this PR ports the logic included at #178 to the mux-based routers
> MUX: use the canonical version of the received header for the lookup

- proxy/shadow.go
- proxy/shadow_test.go
so, a shadow backend is defined as:
```
...
{
"endpoint": "/xyz",
"backend": [
// actual backend
{
"host": [ "http://127.0.0.1:8080" ],
"url_pattern": "/xyz"
},
// backend expecting shadow requests
{
"host": [ "http://127.0.0.1:8088" ],
"url_pattern": "/xyz",
"extra_config": {
"github.com/devopsfaith/krakend/proxy": {
"shadow": true
}
}
}
]
}
...
```
> shadow extra config added to the proxy namespace

- proxy/merging.go
- proxy/merging_test.go
- test/integration_test.go
- test/krakend.json
> abort a sequential merge after the first error or incomplete response

- docs/BENCHMARKS.md
This commit fixes a minor typo in the docs.  No tests are required.  No code is changed.
https://www.merriam-webster.com/dictionary/grouping
> Fix typo in benchmarks

- proxy/balancing.go
- proxy/balancing_benchmark_test.go
this PR uses strings.Builder instead of custom building strategies at the balancer middleware.
since the release of the 1.10 version of the go language introduced the `strings.Builder` struct, its performance has been improved and tests say it's time to adopt this implementation.
The changes introduced in this PR reduce the number and the size of the required memory allocations requested by this mw, relaxing the memory gc requirements
> use strings.Builder for url building

- proxy/merging.go
- proxy/merging_benchmark_test.go
- proxy/merging_test.go
```
$ go test -bench BenchmarkNewMergeDataMiddleware_sequential -benchmem
```
  | bench_fmt.txt | bench_type.txt | delta | conf
-- | -- | -- | -- | --
with_2_parts-8 | 6.07µs ± 1% | 5.80µs ± 3% | −4.45% | (p=0.002 n=6+6)
with_3_parts-8 | 13.7µs ± 1% | 13.2µs ± 4% | −3.89% | (p=0.026 n=6+6)
with_4_parts-8 | 25.6µs ± 1% | 24.0µs ± 1% | −5.94% | (p=0.004 n=6+5)
with_5_parts-8 | 40.9µs ± 0% | 38.9µs ± 2% | −4.98% | (p=0.004 n=5+6)
with_6_parts-8 | 58.8µs ± 0% | 55.6µs ± 3% | −5.37% | (p=0.004 n=5+6)
with_7_parts-8 | 80.2µs ± 0% | 77.0µs ± 4% | ~ | (p=0.082 n=5+6)
with_8_parts-8 | 107µs ± 0% | 102µs ± 3% | −4.97% | (p=0.002 n=6+6)
with_9_parts-8 | 135µs ± 0% | 129µs ± 4% | −4.72% | (p=0.004 n=5+6)
with_10_parts-8 | 166µs ± 0% | 157µs ± 5% | −5.63% | (p=0.002 n=6+6)
[Geo mean] | 46.4µs | 44.1µs …
> sequential merger: use a type switch instead of always going with fmt

- proxy/http.go
- proxy/http_test.go
as requested at #129 and #234 this PR propagates the `Content-Length` header to the backend request if it is present in the proxy request (it must be forwarded there explicitly using the `headers_to_pass`)
> propagate the content length if present

- config/config.go
- config/config_test.go
avoid counting output params referred to a response value, so sequential backends are not required to have input params
> Sequential backends should not require input params

- router/gin/endpoint.go
- router/mux/endpoint.go
- test/integration_test.go
This PR prevent KrakenD from overriding the User-Agent, if the user wants to forward that header (if he specifies `User-Agent` or `*` and the header is present)
> Push KrakenD User-Agent only if not overriding forwarded Header

- transport/http/server/plugin/server.go
This PR adds support for loading more than one http handler plugin per gateway instance.
Plugins will be wrapping the gateway handler in the order they are declared, so given this configuration
```
"name": ["plugin-a", "plugin-b"]
```
the plugin-a will wrap the handler and the plugin-b will wrap the plugin-a
> Support for adding several http handler plugins

- proxy/http_response.go
- proxy/http_response_test.go
this PR inspects the `Content-Encoding` header in order to decompresses gzipped responses before parsing them
> support gzipped responses

- sd/dnssrv/subscriber.go
- sd/dnssrv/subscriber_test.go
use the weight of the SRV record to generate the list of hosts when resolving a service name
> Weighted hostnames

- proxy/request.go
- proxy/request_test.go
clone also the request body in the CloneRequest method, so shadow backends get the same body sent to regular backends
> clone the request body

- transport/http/client/plugin/doc.go
> client plugin example fixed

- encoding/encoding_test.go
- encoding/json.go
- encoding/json_benchmark_test.go
- encoding/json_test.go
- encoding/register.go
```
$ go test -bench . -benchmem -benchtime 10s
goos: darwin
goarch: amd64
pkg: github.com/devopsfaith/krakend/encoding
BenchmarkDecoder/json-collection/collection-8         	 7517224	      1605 ns/op	    1472 B/op	      17 allocs/op
BenchmarkDecoder/json-collection/map-8                	 7459869	      1606 ns/op	    1472 B/op	      17 allocs/op
BenchmarkDecoder/json-map/collection-8                	17147770	       710 ns/op	     992 B/op	       6 allocs/op
BenchmarkDecoder/json-map/map-8                       	16881831	       704 ns/op	     992 B/op	       6 allocs/op
BenchmarkDecoder/safe-json-collection/collection-8    	 8487573	      1407 ns/op	    1504 B/op	      19 allocs/op
BenchmarkDecoder/safe-json-collection/map-8           	 8509557	      1406 ns/op	    1504 B/op	      19 …
```
> safe json decoder added

- router/chi/router.go
- router/gin/router.go
- router/helper.go
- router/helper_test.go
- router/mux/router.go
- test/integration_test.go
- test/krakend.json
You can use now the sequential proxy with POST, PUT and DELETE methods if you only use GET methods before.
#359
> Allow "sequential proxy" work with POST, PUT and DELETE methods

- config/config.go
- config/parser.go
- transport/http/server/server.go
- transport/http/server/server_test.go
This PR introduces support for mTLS between clients and the KrakenD gateway
> mTLS on the server

- router/chi/router.go
- router/gin/router.go
- router/mux/router.go
- test/integration_test.go
this PR introduces a new gateway endpoint at `/__health` for probing the readiness of the gateway
> Add a health check endpoint

- proxy/merging.go
- proxy/merging_test.go
if a previous response in the sequential merging has a collection that must to be passed as url param in the next request, the collection will be formatted as a comma-separated list like this one: "foo,bar,foobar"
> better formatting of arrays when used as req params

- router/chi/endpoint_test.go
- router/gin/endpoint.go
- router/gin/endpoint_test.go
- router/mux/endpoint.go
- router/mux/endpoint_test.go
- test/integration_test.go
This PR will pass original Host header received by KrakenD as X-Forwarded-Host to backend services in the same way X-Forwarded-For is sent
> pass original request host in X-Forwarded-Host header

- proxy/merging.go
If the sequential proxy is in use, copy the body into a new buffer in order to avoid interrupting the normal performance of the krakend gateway.
Fixes issue #426
> copy body if sequential proxy is used

- README.md
* correct some sentences, to read better.
* rename golang to Go.
* capitalize the name "Go"
> small fixes to the README

- config/config.go
... in order to remove noise at the calculated hash
> ignore the cfg name when extracting the hash

- docs/CONFIG.md
As lura evolves, the configuration documentation should be upgraded as well, as beginners usually give preference to newer versions
> upgrade config to version 2

- README.md
Fix a typo on the README file for the link to the CONTRIBUTING.md document
> Fix typo on README file

- proxy/http_response_test.go
- router/chi/endpoint_benchmark_test.go
- router/chi/router_test.go
- router/gin/endpoint_benchmark_test.go
- router/gin/router_test.go
- router/gorilla/router_test.go
- router/httptreemux/router_test.go
- router/mux/endpoint_benchmark_test.go
- router/mux/router_test.go
- router/negroni/router_test.go
- transport/http/client/plugin/plugin_test.go
- transport/http/server/plugin/plugin_test.go
> Replace http.NewRequest nil body for http.NoBody.

- config/config.go
- config/config_test.go
- transport/http/server/server.go
Sets the http client tls configuration to allow insecure connections to the backends for development when using self-signed certificates (enables InsecureSkipVerify).
> Add configuration option allow_insecure_connections

- router/gin/engine.go
- router/gin/engine_test.go
so handler and client plugins can use the same context and share values between them.
> Enable the gin context fallback

- config/config.go
- config/parser.go
- transport/http/server/server.go
- transport/http/server/server_test.go
- transport/http/server/tls_test.go
to narrow down the list of valid CA certificates.
Fixes #596 
> Add the configuration option to not load the systems certificate CA pool

- transport/http/server/plugin/server.go
Do not abort the handler plugin injection if one of them returns an error when creating the handler (an error can be that no config exists).
Fixes #631 
> Do not abort the handler plugin injection

- proxy/plugin.go
- proxy/plugin_test.go
If a badly written third party request / response modifier plugin returns a nil function Lura could panic, so we add a check before adding if to the stack of request / response modifiers.
> Check function provided by request response modifier plugin is not nil

- config/config.go
- config/config_test.go
- config/parser.go
- transport/http/server/server.go
- transport/http/server/server_test.go
- `PreferServerCipherSuites` from config, as it is deprecated and has no effect (but not removed to keep contract): https://pkg.go.dev/crypto/tls#Config:
```go
// PreferServerCipherSuites is a legacy field and has no effect.
//
// It used to control whether the server would follow the client's or the
// server's preference. Servers now select the best mutually supported
// cipher suite based on logic that takes into account inferred client
// hardware, server hardware, and security.
//
// Deprecated: PreferServerCipherSuites is ignored.
PreferServerCipherSuites [bool](https://pkg.go.dev/builtin#bool)
```
- Add `ClientTLS` struct to configure global TLS options for the http client that will be used to connect to backends.
- `AllowInsecureConnections` now is part of the `client_tls` …
> Add client TLS Config

- router/gin/endpoint.go
- router/gin/engine.go
This PR adds support for a global `ErrorResponseWriter` that can be used to write custom error responses for failed requests. I saw that errors can provide encoding information as implemented [here](https://github.com/moritzploss/lura/commit/03d7fab590334bf0fd28c71b21110937acf723b1), but I couldn't figure out how to use that feature and cover all potential error cases, including internal server errors. I'd also need to be able to set custom headers for failed requests. Let me know if you think there's a better way to achieve this!
> add injectable error response writer

- router/gin/endpoint.go
- router/gin/engine.go
- router/gin/engine_test.go
Fix minor bug that was introduced [here](https://github.com/luraproject/lura/pull/659): If a request is aborted with `error: encoded url params`, the status code should be set to `400` (currently returns `200`, but correctly aborts the request). To avoid similar issues, it's generally preferable to set the response status before calling `ErrorResponseWriter`.
> add tests for error response writer

- CONTRIBUTING.md
- README.md
- docs/README.md
Remove links to examples in `docs/README.md` that are no longuer valid, and fix badge and fork link.
> fix broken links in documentation

- transport/http/server/server.go
If the `allow_insecure_connections` global flag is enabled and no `client_tls` section is defined, the TLS initialization panics
> initialize the ClientTLS if required

- config/config.go
- config/parser.go
- transport/http/server/server.go
- transport/http/server/server_test.go
With this changes Lura should be able to provide client certificates to the backend service.
> Add mTLS config for backend clients

- config/config.go
- config/config_test.go
- config/parser.go
- proxy/factory.go
- proxy/headers_filter_test.go
- proxy/query_strings_filter.go
- proxy/query_strings_filter_test.go
In order to be "consistent" with the feature of filtering headers at the backend level, this PR adds filtering of query strings at the backend level too. The name for it is the same as for the endpoint level: `input_query_strings`.
> add backend level query strings filtering

- router/gin/router.go
Remove call to force initialization in gin that was not happening in other parts.
This has been fixed in gin and is not needed anymore.
> Remove gin pending fix "patch"

- config/config.go
- config/config_test.go
- config/parser.go
- transport/http/server/server.go
(defaults to 0.0.0.0).
https://github.com/krakend/krakend-ce/issues/803
> Allow to configure the listen address of the service

- config/config.go
- config/config_test.go
- router/gin/engine.go
- transport/http/server/server.go
- transport/http/server/server_test.go
This solves [#786](https://github.com/krakend/krakend-ce/issues/786) issue in krakend-ce repo.
Move support for h2c from gin router init to http server
init.
If we initialize h2c using gin router it will use h2c handler
to wrap handler with all routes registered on gin router.
The problem is that it is possible to construct router factory
with RunServer function which will wrap h2c handler with additional
handler. Any logic in this handler will not be able to understand
http2 cleartext requests.
We have this example in krakend-ce repository where CORS support
is added through RunServer function. Then we have CORS handler ->
h2c handler -> Gin router.
Simplest fix is to move h2c support to server initialization
and add h2c handler as the outermost layer.
> Fix h2c support

- config/config.go
- config/parser.go
- transport/http/server/server.go
- transport/http/server/server_test.go
Change the list of lists for the certificate and private keys used by the client for `mTLS` with the backend services.
> Name explicitly the client certificate and private key

- config/config.go
- config/config_test.go
In [#694](https://github.com/luraproject/lura/pull/694) I fixed issued with h2c support and CORS. There was small bug which slipped through code review. New config field does not use correct struct tag.
Changed `json` to `mapstructure`.
> Fix for parsing use_h2c config

- config/parser.go
fix missing h2c flag from parser to config
> fix missing h2c flag from parser to config

- config/config.go
- proxy/concurrent.go
- proxy/graphql.go
- proxy/headers_filter.go
- proxy/http.go
- proxy/plugin.go
- proxy/query_strings_filter.go
- transport/http/client/plugin/executor.go
Add `ParentEndpoint` to `Backend` config structure, so logs about a backend can identify where the issue is (to allow identification when the same remote call pattern is used in different endpoints).
> Add parent endpoint info to Backend

- config/config.go
- proxy/concurrent.go
- proxy/graphql.go
- proxy/headers_filter.go
- proxy/http.go
- proxy/plugin.go
- proxy/query_strings_filter.go
- transport/http/client/plugin/executor.go
Related to this PR: https://github.com/luraproject/lura/pull/702/files , where we added the parent endpoint, I found that we should have added the request method in order uniquely identify the parent endpoint.
> Add parent endpoint method to backend logs.

- proxy/plugin.go
- proxy/plugin/modifier.go
- proxy/plugin/modifier_test.go
- proxy/plugin/tests/logger/main.go
Also extend the structs passed to the modifier functions so it can retrieve the execution Context. Reponse modifers now have access to the Request. Updated examples to show the new features.
> Pass the application context to the request and response modifiers.

- proxy/concurrent.go
> fix log messages

- config/config.go
- config/config_test.go
> feat: add overwrite functionality for invalid Pattern

- proxy/balancing.go
- proxy/concurrent.go
- proxy/factory_test.go
- proxy/merging.go
- proxy/request.go
- proxy/stack_test.go
> requests should be cloned at the split/merge and concurrent mw only

- config/config.go
- config/parser.go
- transport/http/server/server.go
- transport/http/server/server_test.go
- transport/http/server/tls_test.go
- Add an aditional `keys` field in `TLS` config, to be able to provide several certificates.
> Support multiple certs

- config/config.go
- config/config_test.go
- config/parser.go
- sd/dnssrv/subscriber.go
Add config option to tweak the DNS cache TTL
> Add config option to tweak the DNS cache TTL

- proxy/shadow.go
- transport/http/server/server.go
- transport/http/server/server_test.go
Removing potential race warnings as detected here: https://github.com/krakend/krakend-ce/issues/945
> Remove race warnings

- router/gin/render.go
Adding `application/x-yaml` as a valid negotiated output encoding
> Enabling yaml to negotiated encoding

- router/gin/endpoint.go
- router/gin/endpoint_test.go
Added a way to write response headers on error
If the triggered error implements a `Headers() map[string][]string`, the returned map will be written as response headers. For example, when implementing a quota system, you could return a 429 with a `Retry-After` response header like this:
```
type errProxyQuotaExceeded struct {
error
headers map[string][]string
}
func NewErrProxyQuotaExceeded(blockedFor string) error {
err := errProxyQuotaExceeded{error: errors.New("quota exceeded")}
err.headers = map[string][]string{
'Retry-After': {blockedFor},
}
return err
}
func (errProxyQuotaExceeded) StatusCode() int {
return http.StatusTooManyRequests
}
func (e errProxyQuotaExceeded) Headers() map[string][]string {
return e.headers
}
```
> Add new error type to send response headers
