luraproject/lura

router/gin/endpoint.go
router/gin/router.go

so middlewares and enpoint decorators can be added to the router factory

Create a Gin endpoint factory

---

.gitignore
examples/gorilla/Makefile
examples/gorilla/README.md
examples/gorilla/main.go
examples/mux/main.go
router/mux/router.go

#10 requested some modifications into the `mux` router factory implementation. The changes don't affect the interfaces and exposed methods of the package but I think they'll support other integrations in the future

Add support to gorilla/mux

---

.gitignore
Makefile
README.md
examples/negroni/Makefile
examples/negroni/README.md
examples/negroni/main.go

#11 requested for an example of how to integrate the negroni middlewares into the KrakenD. As this PR shows, it just requires a custom engine properly instantiated

Add negroni integration example

---

config/config.go
examples/gorilla/main.go
router/mux/endpoint.go

support gorilla routing patterns as requested in #14

gorilla routing patterns

---

Makefile
examples/gorilla/Makefile
examples/gorilla/main.go
router/gorilla/router.go

Moved the Gorilla example to its own package.

Add gorilla router package

---

.travis.yml
config/config.go
examples/gin/main.go
proxy/balancing.go
proxy/balancing_test.go
proxy/factory.go
sd/dnssrv/subscriber.go
sd/dnssrv/subscriber_test.go
sd/loadbalancing_test.go
sd/subscriber.go

As requested in #8, this PR adds a subscriber for a Service Discovery system based on DNS SRV records

Support DNS SRV

---

router/gin/debug_test.go
router/gin/endpoint_test.go
router/gin/router.go
router/gin/router_test.go
router/gorilla/router_test.go
router/mux/debug.go
router/mux/debug_test.go
router/mux/endpoint.go
router/mux/endpoint_test.go
router/mux/router.go
router/mux/router_test.go
router/router.go

add some integration test for all the router adapters available in the framework

Router integration tests

---

.gitignore
Makefile
examples/dns/Makefile
examples/dns/README.md
examples/dns/main.go

... so both examples will display different framework features

separate the DNS example from the standard GIN example

---

.gitignore
Makefile
config/config.go
config/config_test.go
encoding/rss.go
encoding/rss_test.go
examples/rss/Makefile
examples/rss/README.md
examples/rss/main.go

Add new decoder for RSS feeds, so KrakenD can also consume data from this type of backends and datasources
This PR also comes with an interesting example! Total WIN! 😉

Rss decoder

---

.gitignore
Makefile
README.md
examples/jwt/Makefile
examples/jwt/README.md
examples/jwt/main.go

This PR adds an example of a very secure (but without SSL) implementation by using:
- CORS middleware
- JWT validation middleware with `HS256` (and a dummy issuer)
- General security middleware enforcing some standards such as host validation, SSL redirects, STS, etc

JWT example

---

Makefile
examples/etcd/Makefile
examples/etcd/README.md
examples/etcd/main.go
sd/etcd/client.go
sd/etcd/client_test.go
sd/etcd/subscriber.go
sd/etcd/subscriber_test.go

Add a etcd subscriber for the SD module, so backends can be loaded from etcd

Add etcd subscriber

---

sd/etcd/client_test.go

update the implementation of the etcd client interface

---

.travis.yml

run the travis build also with golang 1.9

add golang 1.9 to the version list

---

config/config.go
config/config_test.go
config/uri.go
config/uri_test.go

allow not strict rest urls

---

config/config.go
config/parser.go
router/gin/router.go
router/mux/router.go

config params added so the user can configure the timeouts of the http server (https://golang.org/pkg/net/http/#Server)

http server timeouts added

---

proxy/http.go
proxy/http_executor.go
proxy/http_response.go
proxy/http_status.go

split the http proxy components across several files for easier management

http proxy refactor

---

router/gin/endpoint.go
router/mux/endpoint.go
router/router.go

Allow clients to inject their own proxy error to HTTP status code translator

Http error translator

---

docs/BENCHMARKS.md
router/gin/debug_test.go
router/gin/endpoint.go
router/gin/endpoint_benchmark_test.go
router/gin/endpoint_test.go
router/mux/debug_test.go
router/mux/endpoint.go
router/mux/endpoint_benchmark_test.go
router/mux/endpoint_test.go
router/router.go

Prepare cache headers at building stage (before start working)

prepare the cache header at building stage

---

proxy/merging.go

The combinedData() function does not use Context.

combineData() does not need Context

---

config/config.go
config/parser.go
router/gin/endpoint.go
router/mux/endpoint.go

as described in #82 , this PR adds a list of headers to be passed to the backend if present in the client request

editable list of headers to pass to the backend

---

router/gin/endpoint_test.go

test the context values are passed from the router to the proxy layer. closes #90

Pass context from the router to the proxy

---

encoding/encoding.go
encoding/encoding_test.go
encoding/string.go
encoding/string_test.go

string decoder from the raw_encoding branch

String decoder

---

Makefile
proxy/proxy_test.go

Run the tests with the race detector enabled.

race detector enabled

---

proxy/merging.go
proxy/merging_benchmark_test.go
proxy/merging_test.go

as requested in #117, this PR introduces incremental merging for async response combining

Async merge

---

config/config.go
config/config_test.go
encoding/encoding.go
encoding/encoding_test.go
encoding/register.go
proxy/http.go
proxy/http_response.go
proxy/http_response_test.go
proxy/http_test.go
router/gin/render.go
router/gin/render_test.go
router/mux/render.go
router/mux/render_test.go

So the gateway can operate as a request router

nop decoder and renders added

---

proxy/http.go
proxy/http_status.go

no-op http status handler added

---

.gitignore
config/config.go
config/parser.go
router/gin/router.go
router/gin/router_test.go
router/gorilla/router_test.go
router/mux/router.go
router/mux/router_test.go
router/negroni/router_test.go
router/router.go

as requested in #95 , this PR exposes all the http server and transport config values

expose all the http config values

---

logging/log.go

This implements the NoOp logger.

Add the NoOp Logger.

---

proxy/formatter.go
proxy/formatter_benchmark_test.go
proxy/formatter_test.go
proxy/http.go

minor refactor setting the bases for future improvements

pass a backend definition to the formater

---

router/gin/endpoint.go
router/gin/endpoint_test.go
router/mux/endpoint.go
router/mux/endpoint_test.go

as pointed at https://github.com/devopsfaith/krakend-ce/issues/32, the error returned by the proxy should not have preference over an incomplete response when building the router response

check the proxy response before returning an error

---

encoding/encoding.go
plugin/register.go
plugin/tests/app/main.go
proxy/formatter.go
proxy/register_test.go
router/mux/engine.go
sd/register.go

minor fixes: typos, lint errors and other minor notices

Goreportcard fix

---

proxy/http_executor.go

this PR removes the hard limit for the http client timeout

http client timeout

---

config/parser.go

file reader added to the default config parser so custom behaviours can be injected

Config: Accept custom file readers

---

router/mux/endpoint.go
test/integration_test.go
test/krakend.json

This PR adds the negroni and the gorilla routers into the integration test suite

Extend integration tests

---

config/config.go
proxy/merging.go
proxy/merging_test.go
test/integration_test.go
test/krakend.json

This PR fixes the bug identified at #194

Fix sequential url check

---

config/config.go

... in order to recover from weird config parser errors like #198

simple extra config sanitization added

---

Makefile

Update dep version

---

proxy/balancing.go
proxy/balancing_test.go
proxy/request.go

this PR fixes the tests failing at #171

Support mixing optional and mandatory querystring

---

config/config.go
config/config_test.go

... when checking output params

Config init: avoid creating an intermediate map

---

proxy/merging.go
proxy/merging_test.go

so `resp0_struct.foo` can be used to extract the `foo` field from the `struct` key

multilevel selection of parameters for sequential pipes

---

transport/http/client/plugin/executor.go
transport/http/client/plugin/plugin.go

This PR introduces a new HTTP request executor able to use injected golang plugins during the request execution

HTTP request executor plugin

---

plugin/plugin.go
transport/http/client/plugin/executor.go
transport/http/client/plugin/plugin.go
transport/http/server/plugin/plugin.go
transport/http/server/plugin/server.go

This PR introduces a new HTTP handler able to use injected golang plugins during the initial request handling by the http router

Http handler plugin

---

Gopkg.lock

this PR closes #264 (related to devopsfaith/flatmap#5)

flatmap module updated

---

router/gin/render.go
router/gin/render_test.go
router/mux/render.go
router/mux/render_test.go

Fix issue https://github.com/devopsfaith/krakend/issues/279

Return all headers from proxy response

---

transport/http/client/plugin/doc.go
transport/http/server/plugin/doc.go

this pr adds examples of http plugin implementations
it also covers https://github.com/devopsfaith/krakend-documentation/issues/50

godoc for http plugin packages added

---

go.mod
go.sum
proxy/balancing.go
proxy/factory.go
sd/loadbalancing.go
sd/loadbalancing_benchmark_test.go
sd/loadbalancing_test.go

this PR improves the random LB by replacing the rnd generator from the stdlib with a more performant one.
It also introduces a strategy for selecting the best LB depending on the server. If there is 1 core, it sticks with the round robin

Optimized LB

---

config/config.go
config/parser.go
test/integration_test.go
test/krakend.json

nested sequential params parsing fixed

---

router/gin/render.go
router/gin/render_test.go
router/mux/render.go
router/mux/render_test.go

do not copy nil readers

---

config/config.go
proxy/formatter.go
test/doc.go

this PR fixes some minor typos

fix ineffassign and misspell errors

---

proxy/formatter.go
proxy/formatter_test.go

This PR adds support for setting targets nested in complex structs such as `foo.bar.foobar`

nested targets

---

config/config.go
config/config_test.go
config/parser.go

this pr adds a deprecation notice to the `config.Backend.Whitelist` and the `config.Backend.Blacklist`, replacing them with the `config.Backend.AllowList` and the `config.Backend.DenyList`

allow and deny lists added

---

proxy/balancing.go
proxy/balancing_test.go

avoid the extra ampersand

---

proxy/factory.go
proxy/formatter.go
proxy/formatter_test.go

flatmap proxy added

---

config/config.go
config/config_test.go
router/chi/endpoint.go
router/gin/endpoint.go

this PR add support for injecting `JWT` params into the backend url pattern

Jwt param extractor

---

config/config.go

fix config backend:  allow <=> deny;

---

logging/log.go

This PR deals with the issue reported at #450

avoid using the default logger from the stdlib

---

proxy/formatter.go
proxy/formatter_test.go

this PR extends the flatmap `del` operation so it accepts more than one pattern to be removed

flatmap del operation accepts more than one argument

---

router/gin/router.go

create a group for the declared endpoints so mw are injected just to the group

Group all the declared endpoints

---

docs/slides/krakend-overview.slide

Fix typo in slides

---

router/gin/render.go
router/mux/render.go

`json-collection` added as a valid output encoding for collections

Return collections with json

---

proxy/factory.go
proxy/plugin.go
proxy/plugin/modifier.go
proxy/plugin/modifier_test.go
proxy/plugin/tests/main.go
proxy/plugin_test.go

This PR introduces 2 new types of plugins:
1. request modifiers
2. response modifiers
both types of plugins can be injected at the beginning and/or the end of the proxy pipe

Request and response modifier plugins

---

router/gin/router.go

so the handler for 404 and 405 can be defined

do not set a default noroute handler

---

config/config.go
core/version.go
logging/log.go
plugin/plugin.go
proxy/plugin/modifier.go
proxy/proxy.go
register/register.go
router/chi/router.go
router/gin/router.go
router/gorilla/router.go
router/httptreemux/router.go
router/mux/router.go
router/negroni/router.go
router/router.go
sd/dnssrv/subscriber.go
sd/subscriber.go
test/doc.go
transport/http/client/executor.go
transport/http/server/server.go

pkg doc fixed

---

transport/http/server/server.go
transport/http/server/server_test.go

tls 1.3 added

---

proxy/static.go
proxy/static_test.go

check if the data field is null before adding the static values

---

config/config.go
proxy/graphql.go
proxy/merging.go
proxy/plugin.go
proxy/request_test.go
sd/loadbalancing_test.go
transport/http/client/graphql/graphql.go
transport/http/client/status.go

Code improvements

---

router/gin/engine.go

so by default no url encoded params will be accepted

param validator middleware

---

config/parser.go

Signed-off-by: Nodar Jarrar [nodar963@gmail.com](mailto:nodar963@gmail.com)

add DisableStrictREST to parseableServiceConfig

---

encoding/encoding.go
encoding/json_test.go

place the basic values under the content key

---

router/gin/endpoint.go
router/mux/endpoint.go

Signed-off-by: Sumit Tembe <sumit.tembe@outlook.com>

proxy: retain original request path in proxy.Request

---

config/config.go
router/chi/endpoint.go
router/gin/endpoint.go
router/gorilla/router.go
router/httptreemux/router.go
transport/http/client/graphql/graphql.go

Signed-off-by: Sumit Tembe <sumit.tembe@outlook.com>
Fixes: #586

chore: Switch from strings.Title to cases.Title

---

router/gin/endpoint.go

Add endpoint error to Gin context

---

config/config.go
router/gin/endpoint.go

Create the cases.Caser outside the returned function.

---

router/gin/endpoint.go

log all the router errors with the app logger

---

transport/http/server/server.go

Add a new factory to return a RunServer with a logger.

---

config/config.go
config/parser.go

debug cfg param renamed

---

config/parser.go

fix cachettl type

---

router/gin/render.go

select the render from the register instead of using a hardcoded function

Improve render selection when negotiating

---

README.md

Signed-off-by: Daniel López <dlopez@krakend.io>

remove the reference to the examples folder

---

.github/workflows/go.yml

use go 1.19 for the CI

---

config/config.go

so it can use a custom pattern.

Add a setter to the sequentialParamsPattern 

---

proxy/shadow.go
proxy/shadow_test.go

Set the timeout in the context sent to the shadow proxy request

---

config/config.go
config/config_test.go

Improve the validation of the endpoint patterns

regexp improved

---

router/gin/engine.go

If not explicitly defined in the configuration.

Fix: maintain the router configuration defaults

---

router/gin/echo.go
router/gin/echo_test.go
router/mux/echo.go
router/mux/echo_test.go

since it will always be empty.

Remove the scheme from the echo endpoint response

---

proxy/graphql.go

graphql backend: force content type to application/json

graphql backend: force content type to application/json

---

proxy/graphql.go
transport/http/client/graphql/graphql.go

Log error when bad graphql config is provided

Log error when bad graphql config is provided

---

backoff/backoff.go
config/config.go
proxy/http.go
proxy/shadow.go
router/mux/engine.go

I was reading the code and saw some typos, just that.
Thank you!

Fix: Some typos

---

config/config.go
config/config_test.go
config/parser.go
sd/dnssrv/subscriber.go
sd/dnssrv/subscriber_test.go

Fixes: https://github.com/luraproject/lura/issues/667

Add https option to dnssrv

---

config/config.go
config/config_test.go
config/uri.go
proxy/balancing.go
proxy/balancing_benchmark_test.go
proxy/balancing_test.go
proxy/concurrent.go
proxy/concurrent_test.go
proxy/factory.go
proxy/formatter.go
proxy/graphql.go
proxy/headers_filter.go
proxy/http.go
proxy/http_test.go
proxy/logging.go
proxy/logging_test.go
proxy/merging.go
proxy/merging_test.go
proxy/plugin.go
proxy/proxy.go
proxy/proxy_test.go
proxy/shadow.go
proxy/static.go
proxy/static_test.go

Reduce the chance of panicking when a sensible behavior can be used, while emitting an error.

Avoid panics

---

proxy/balancing.go
proxy/http.go

- build the final url directly
- remove unrequired clone

Minor optimizations

---

core/version.go

Get go version from runtime

---

router/gin/router.go

If there is an error building a proxy pipeline, instead of skiping the endpoint (and thus, getting a 404 when making a request to it), we add a handler that returns `500 Internal Server Error` code.

500 error for failed proxy pipelines buildings
